name: 'Notify Slack'
description: 'Send workflow notifications to Slack'

inputs:
  webhook-url:
    required: true
  status:
    required: true
  channel:
    default: ''

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook-url }}
      run: |
        case "${{ inputs.status }}" in
          success) EMOJI="✅"; COLOR="good" ;;
          failure) EMOJI="❌"; COLOR="danger" ;;
          *) EMOJI="ℹ️"; COLOR="warning" ;;
        esac
        
        curl -s -X POST -H 'Content-type: application/json' \
          --data "{
            \"attachments\": [{
              \"color\": \"$COLOR\",
              \"text\": \"$EMOJI ${{ github.workflow }} ${{ inputs.status }}\",
              \"fields\": [
                {\"title\": \"Repository\", \"value\": \"${{ github.repository }}\", \"short\": true},
                {\"title\": \"Branch\", \"value\": \"${{ github.ref_name }}\", \"short\": true}
              ]
            }]
          }" "$SLACK_WEBHOOK"
